version: '3'
services:
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: wf_nginx_container
        restart: unless-stopped
        tty: true
        ports:
          - "4000:80"
        volumes:
          - ./src:/var/www/
          - .docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
          - app

    #PHP Service
    app:
        build: .docker/php
        container_name: wf_app_container
        volumes:
          - ./src:/var/www/
          - .docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
        tty: true
        #environment:
          #- maildev_host=wf_maildev_container
        working_dir: /var/www
        depends_on:
          #- maildev
          - mysql   
           
    #MySQL Service
    mysql:
        image: mysql:8
        container_name: wf_mysql_container
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        ports:
          - "4004:3306"
            
    #PHP-MyAdmin MYSQL
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wf_phpmyadmin_container
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 4001:80
        links:
            - mysql

    #Mail_Host
    #maildev:
        #image: djfarrelly/maildev
        #container_name: wf_maildev_container
        #ports:
          #- 4002:80